spring.application.name=monitoring-backend
server.port=${PORT:8080}

# PostgreSQL Connection
spring.datasource.url=${DB_URL:jdbc:postgresql://192.168.56.104:5432/monitoring_db}
spring.datasource.username=${DB_USER:monitoring_user}
spring.datasource.password=${DB_PASS:123456}

# HikariCP Resilience
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.leak-detection-threshold=2000
spring.datasource.hikari.initialization-fail-timeout=-1

# Hibernate & JPA Resilience
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=true
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Prometheus URL
prometheus.url=${PROMETHEUS_URL:http://192.168.56.101:9090}

# Actuator Monitoring
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Expose errors for debugging
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-exception=true

# SSH Pull Service Config
ssh.user=${SSH_USER:pfeadmin}
ssh.password=${SSH_PASS:123456}